# Generated by Django 3.1 on 2020-08-06 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pis_ledger', '0009_ledger_invoice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ledger',
        ),
    ]
