# Generated by Django 3.1 on 2020-08-13 00:45

from django.db import migrations
from django.contrib.auth.models import User

def defaultUser(apps, schema_editor):
    """
    Migration of a default user
    :return:
    """
    user = User.objects.create_user(username='admin', password='partum123')
    user.first_name = 'admin'
    user.last_name = 'admin'
    user.save()

def defaultRetailer(apps, schema_editor):
    retailer = apps.get_model('pis_com','Retailer')
    retailer = retailer()
    retailer.name = "Partum Solutions"
    retailer.slug = "Partum Solutions"
    retailer.save()

def retailerUser(apps,schema_editor):
    retailer_user = apps.get_model("pis_com", "RetailerUser")
    retailer_user = retailer_user()
    retailer_user.retailer_id = 1
    retailer_user.user_id = 1
    retailer_user.role_type = "owner"
    retailer_user.save()

def adminconfiguration(apps,schema_editor):
    admin = apps.get_model("pis_com","AdminConfiguration")
    admin = admin()
    admin.demo = 1
    admin.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pis_com', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(defaultUser),
        migrations.RunPython(defaultRetailer),
        migrations.RunPython(retailerUser),
        migrations.RunPython(adminconfiguration)
    ]
